[build]
  publish = "dist"
  command = "deno run --allow-read --allow-write build.ts"

[[redirects]]
from = "/"
to = "api.json"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
