description: Collection of CSS Shapes with clean and reusable code. Based on the Smashing Magazine article.
author:
  name: Temani Afif
  url: "https://www.smashingmagazine.com/2024/05/modern-guide-making-css-shapes/"
